name: reward_boy
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  share_plus: ^10.0.2
  flutter_fortune_wheel: ^1.3.1
  url_launcher: ^6.3.0
  dio: ^5.7.0
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  advertising_id: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
